ecs_cluster_name = "siewlee-ecs-cluster-prod"
ecs_service_name = "siewlee-ecs-service-prod"
ecs_task_defn_family = "siewlee-ecs-task-def-prod"
ecs_container_name = "siewlee-container-prod"
ecs_port_name = "siewlee-3000-tcp-prod"